### PR TITLE
Update Request.evaluatePreconditions() to match RFC 7232

### LINKED ISSUE #747: Request.evaluatePreconditions(): anything other than "If-None-Match: *" must return 412
The Javadoc for `Request.evaluatePreconditions()` says:

> Note that [...] `If-None-Match: something` will always be considered to have been met

However, [RFC 7232](https://tools.ietf.org/html/rfc7232#section-3.2) says:

> [...] either not having any current representation of the target resource, when the field-value is "*", **or having a selected representation with an entity-tag** that does not match any of those listed in the field-value.

So `Request.evaluatePreconditions()` must return 412 for anything other than "If-None-Match: *"

### PR DESCRIPTION
**Pull request by anthonyvdotbe**
Signed-off-by: Anthony Vanelverdinghe <anthonyv.be@outlook.com>

Fixes #747

### CODE REVIEW

**Comment by chkal** [comment]
@anthonyvdotbe The Eclipse ECA check failed. Did you already sign the [Eclipse CLA](https://www.eclipse.org/legal/ECA.php)?

**Comment by anthonyvdotbe** [comment]
@chkal Yes, I did. The e-mail address of my ECA also matches with the one I used to sign off the commit. I just verified again, and it said I had signed an earlier version of the ECA which expired on March 1st, so I signed the new version 3.0.0 now. If it still doesn't work, any help is welcome.

**Comment by chkal** [comment]
Could you perhaps do an interactive rebase and slightly modify the commit message and then do a force push? Maybe this triggers another validation. I'm not sure what is wrong here. The Eclipse validation tools says this: 

image

**Comment by anthonyvdotbe** [comment]
I just did, but validation still fails. It seems like there are some extra checks for "specification projects":

image

I have contributed to other Eclipse projects before (e.g. [here](https://github.com/eclipse/microprofile-reactive-streams-operators/pull/94)), so I don't know what's wrong.

**Comment by mkarg** [comment]
Possibly new requirements by the EF? Filed an issue, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=540694#c25.

**Comment by andymc12** [comment]
The force-push must've done it.  It looks like it is passing the ECA check now.

**Comment by mkarg** [comment]
@andymc12 Please don't guess. ;-) Actually the EF fixed a wrong email address in their database and re-triggered the IP validation.

**Comment by chkal** [comment]
@mkarg I guess we really need some way to track outstanding changes to the TCK and the spec document.

**Comment by anthonyvdotbe** [comment]
@mkarg thanks for the help in getting the IP validation to work

**Pull request merged**
