### PR TITLE
Use GenericEntity for List<EntityPart> entity in EntityPart javadoc.

### PR DESCRIPTION
**Pull request by jansupol**
Signed-off-by: jansupol <jan.supol@oracle.com>

### CODE REVIEW

**Comment by jansupol** [comment]
The `MessageBodyWriter` would not know `#isWritable(Class<?> type, Type generic,...)` the generic type without this and would not know a list of which entities it is about to process.

**Review by spericas — APPROVED** [review]
Right, that makes sense.

**Review by andymc12 — APPROVED** [review]
LGTM - thanks @jansupol!

**Comment by spericas** [comment]
Merging via fast track as this is a one liner.

**Comment by jimma** [comment]
> The `MessageBodyWriter` would not know `#isWritable(Class<?> type, Type generic,...)` the generic type without this and would not know a list of which entities it is about to process.

@spericas @andymc12 @jansupol Late to look at this PR.  To me, this kind of change should be in api signature instead of only in javadoc.

**Pull request merged**
