### PR TITLE
Initial logo

### PR DESCRIPTION
**Pull request by mkarg**
As announced in the [committer-private mailing list](https://github.com/orgs/eclipse-ee4j/teams/eclipse-jaxrs/discussions/1) at start of this Github project, my wife (graduated designer) contributed an _initial_ logo for the JAX-RS API project.

Signed-off-by: Markus KARG <markus@headcrashing.eu>

### CODE REVIEW

**Comment by spericas** [comment]
There may be issues using Duke in this context. I'll let @m0mus comment on that. I also think we should wait until other things settle down at Apache before even starting our own logo discussion.

**Comment by mkarg** [comment]
@spericas What has Apache to do with that and why can't we use the Duke while Yasson did that?

**Comment by spericas** [comment]
@mkarg I don't know. That is why I said "there may be issues" and not "there will be issues" :-)

**Comment by mkarg** [comment]
Filed [CQ 16051](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16051) so we are safe wrt to legal issues.

**Comment by mkarg** [comment]
@chkal @m0mus Can you please review this PR? You liked the idea to have an initial logo, so here it is... ;-)

**Comment by chkal** [comment]
@mkarg Thanks a lot for taking care of this. And many thanks to your wife for helping us with the logo.

I'm just wondering: Maybe we could skip the initial logo and start some discussion about our ideas for a final logo now? Just to prevent duplicated work.

**Comment by chkal** [comment]
BTW: I'm also a bit disappointed that using Duke in a logo isn't allowed. I wasn't expecting such trouble with Duke as a base for a logo.

**Comment by mkarg** [comment]
@chkal We _may_ use Duke as a logo in general. The EMO's dilemma is that the EF wants to register _all_ logos as trademarks, and Oracle will not allow _that_ for Dukes. Just to clarify.

**Comment by ronsigal** [comment]
I think it's great that @mkarg and his wife made the effort to create a logo. My initial reaction, and maybe I'm missing something, is that Duke (and, by proxy, JAX-RS) is **immobilized** in a spider's web. It seems a little ... inauspicious ... for a project all about rapid and fluid communication. My 2 cents.

Also, Duke always reminds me of the Windows paperclip. ;-)

**Comment by m0mus** [comment]
The logo is good, but I don't think that you can use Duke anywhere in Jakarta projects. Eclipse doesn't own rights to use Duke.

**Comment by mkarg** [comment]
Thanks, Dmitry! :-)

IIRC nobody needs any _special_ rights to use logos derived from Duke, as it originally was published by BSD and is not an Oracle trademark per se, but the EF *simply fears* that one day Oracle comes up with a claim that *any* Duke-derived logos would be "too similar" to one particular trademark of Oracle which also was *derived* from Duke. Oracle so far did not provide a guarantee that this will not happen, so we were *asked* not to use it, but there is no *ban*. Due to that, *some* specifications *do* use the Duke (and had no legal problems in any way so far, like JSON-B's really cool _Jason Duke_), but others hesitate with it (like JAX-RS).

**Comment by mkarg** [comment]
Has the "no-party" been able to provide any _proof or official statement from the EF_ that Duke MUST NOT (not just SHOUD NOT) be used, despite the fact that Duke is not an Oracle trademark while [it is BSD licenced](
https://user-images.githubusercontent.com/1701815/98445738-9608f300-2119-11eb-9191-2bac05de17b2.png)? Otherwise I would say, let's dare using this logo until the EF chimes in actively. I am cc'ing @waynebeaton for that reason.

**Comment by waynebeaton** [comment]
The EF fears nothing.

Project logos are trademarks (referred to as "design marks" in trademark law). We don't always register them as trademarks, but based on the way that they are used (logos are tightly coupled/associated with the corresponding project/specification), they are effectively trademarks (referred to in some jurisdictions as "common law" trademarks). 

Independent of how something is licensed, it is extremely challenging to claim a derivative of somebody else's copyrighted materials as a trademark.

So... while Duke is indeed licensed in a manner that permits derivative works, we cannot reasonably claim a logo with Duke's image as a trademark, and so it cannot be used for a project logo.

Because it is licensed in a manner that permits it, Duke can be used for "interesting artwork" associated with the project. So, for example, it would be perfectly fine to have an image of Duke holding the project logo on the project's landing page.

**Comment by mkarg** [comment]
@waynebeaton It is not true that a project logo *is* a trademark, but it *could* be used as one, and even the EF might *like* to use it as that. Bit we (the project) so far does not plan to use it as a *trademark* (at least I cannot remember we asked the EF to do that for us), but we only use it as a *logo* to show a nice duke on the web site and docs. So IMHO there is no problem at all as long as the EF understands that we *do not want* that this logo is a trademark.

**Comment by waynebeaton** [comment]
You can certainly have an image of Duke laying in a web hammock on a page here-and-there of the project website. If you don't use it as a project logo, then it isn't a project logo.

It's not a matter of whether or not the project team asks. When a project team uses an image as an official project logo, the Eclipse Foundation assumes responsibility for protecting it as a trademark and that logo becomes subject to the Eclipse Foundation Trademark Usage Guidelines.

**Comment by waynebeaton** [comment]
On the topic of trademarks,

Oracle considers "JAX-RS" to be its trademark. There's some background reading in [Mike's blog](https://blogs.eclipse.org/post/mike-milinkovich/update-jakarta-ee-rights-java-trademarks).

Please update the README to use the Jakarta name, "Jakarta RESTful Web Services".

**Comment by mkarg** [comment]
This is not true. I have written permission received directly from Oracle by private email that they abstain from considering "JAX-RS" to be their trademark.

Can you please disclose who of Oracle claimed it?

-Markus

 

 

Von: Wayne Beaton [mailto:notifications@github.com] 
Gesendet: Donnerstag, 19. November 2020 17:46
An: eclipse-ee4j/jaxrs-api
Cc: Markus KARG; Mention
Betreff: Re: [eclipse-ee4j/jaxrs-api] Initial logo (#616)

 

On the topic of trademarks,

Oracle considers "JAX-RS" to be its trademark. There's some background reading in Mike's blog <https://blogs.eclipse.org/post/mike-milinkovich/update-jakarta-ee-rights-java-trademarks> .

Please update the README to use the Jakarta name, "Jakarta RESTful Web Services".

**Comment by mkarg** [comment]
> It's not a matter of whether or not the project team asks. When a project team uses an image as an official project logo, the Eclipse Foundation assumes responsibility for protecting it as a trademark and that logo becomes subject to the Eclipse Foundation Trademark Usage Guidelines.

So in our case, we just have clarified that nobody here actually wants to claim trademark for our project logo, hence there is nothing for the EF to "assume" anymore, hence why still cannot we use it as project logo *now*?

**Comment by waynebeaton** [comment]
I found a better link. The current state regarding project names is described [here](https://jakarta.ee/legal/acronym_guidelines/).

My understanding is that incidental use of the acronyms in specification text is considered okay as long as the specification document describes the acronym (e.g., "References in this document to JMS refer to the Jakarta Message Service unless otherwise noted.").

**Comment by spericas** [comment]
Cleaning up old PR's that have not been approved.

**Pull request closed without merging**
