### PR TITLE
Changed groupId and artifactId. Fixes #663 (master)

### LINKED ISSUE #663: Change Maven coordinates
All current API libraries shipped must be distributed to Maven Central under a sub-package of the `jakarta` groupId. Before the first release Maven coordinates of this project must be changed as it's described [here](https://github.com/eclipse-ee4j/ee4j/wiki/New-Maven-Coordinates).

### PR DESCRIPTION
**Pull request by ggam**
Changing Maven Coordinates according PMC's request.

Closes #663 

**The review period for this change is only five days, as this change is needed rather immediately by the Jakarta build team.**

### CODE REVIEW

**Comment by mkarg** [comment]
@ggam Thank you for chiming in. Next time please respect the assignments: https://github.com/eclipse-ee4j/jaxrs-api/issues/663#issuecomment-422819402, so we do not work on the same issue. Also please write a concise description into your PR. In particular, we now have the problem that you did not mention a voting deadline. So the deadline is two weeks, which is too long as we need this immediately.

**Comment by ggam** [comment]
@mkarg Sorry I was doing it on all repositories and it was fast enough to do it for this too. I can't make the changes until this afternoon (its 7.45 here now) so feel free to close this PR and supersede it with yours.

**Comment by mkarg** [comment]
@ggam No need to be sorry, we all do mistakes (even me). Proposal: We close _this_ PR and you first do finish your work on #666 so I can get that one merged at the end of its review period. Reason: I will do a backport of more commits from `EE4J_8` to `master` anyways after 2.1.2 is released (i. e. October 22 according to PMC), so your work from #666 will be included automatically and nobody has double work. Would that be OK for you?

**Comment by mkarg** [comment]
@arjantijms Can you please move your vote from here to #666? Thanks. :-)

**Pull request closed without merging**
