### PR TITLE
Formatting according to recommended EE4J code conventions

### PR DESCRIPTION
**Pull request by arjantijms**
Formatting of the entire code base according to [recommended EE4J rules](https://github.com/eclipse-ee4j/ee4j/wiki/Code-Conventions).

*Mostly affected the Javadoc.*

### CODE REVIEW

**Comment by mkarg** [comment]
@arjantijms Can you please add a link to the mentioned rules in the description of the PR? Thanks.

**Comment by chkal** [comment]
I agree with @mkarg. I'm also +1 for this, but let's first agree on the concrete rules, how to enforce and where to document them before merging it.

**Comment by mkarg** [comment]
In issue #601 we agreed upon adopting the EE4J formatting rules, and nobody is against applying them to `master` right now. **As a consequence, please everbody review this PR!** :-)

**Comment by mkarg** [comment]
We're about to merge this PR so I'd like to encourage someone to provide a subsequent PR which alignes the Checkstyle configuration accordingly. Otherwise rather soon the actual formatting will deviate again. As we have plenty of committers who had not the chance to contribute in the past months, I assume someone of those is happy to chime in at short notice?

**Comment by mkarg** [comment]
I think it is a good idea if we extend the review time bit, as the discussion in #601 needed a while. So please don't mind that we won't *immediately* merge this (while I am pretty sure that we will agree on accepting the PR). :-)

**Pull request merged**
