### PR TITLE
Allow vendors to add their deployment descriptors to arquillian archives

### PR DESCRIPTION
**Pull request by jansupol**
Signed-off-by: jansupol <jan.supol@oracle.com>

### CODE REVIEW

**Comment by jansupol** [comment]
@scottmarlow @andymc12 This is how the vendor-specific descriptors could be brought into the Arquillian archive. WDYT?

**Comment by arjantijms** [comment]
@jansupol Arquillian has a standard SPI for what I think you're doing here, it's `org.jboss.arquillian.container.test.spi.client.deployment.ApplicationArchiveProcessor`

The Arquillian based JWT TCK describes this as well. See: https://github.com/eclipse/microprofile-jwt-auth/blob/master/tck/README.adoc#creating-your-implementation-tck-harness-artifact

**Comment by jansupol** [comment]
Ok, an alternative approach using ApplicationArchiveProcessor is in #1065.

@arjantijms Thanks for pointing it out.

**Comment by scottmarlow** [comment]
For the many Platform TCK tests, it would be nice to support something like this pr that allows vendors to specify their folder that contains all of their vendor descriptor files for various test packages.  For each test package, we would need to indicate the target archive in some way (whether its a jar, war, ear, rar or whatever) for each contained deployment descriptor.  

The ApplicationArchiveProcessor way seems like a group approach as well.

**Comment by jansupol** [comment]
Closing this in favor of #1065.

**Pull request closed without merging**
