### PR TITLE
[#554] Fix javadoc for Response.created()

### PR DESCRIPTION
**Pull request by ronsigal**
Closes item 1 of issue #554.

### CODE REVIEW

**Comment by mkarg** [comment]
@ronsigal You don't need an sign-off for the PR itself, just for the contained commit(s).

**Comment by chkal** [comment]
I'm basically +1 for this change. However, I'm not sure for which release we should target it. As @spericas already mentioned in #554, this is most likely a spec bug. However, the fix is an incompatible change.

**Comment by ronsigal** [comment]
Hi @chkal,

Actually, there's an argument to be made that it's not really a substantive change. The implementation of Response.created() is
```
    public static ResponseBuilder created(URI location) {
        return status(Status.CREATED).location(location);
    }
```
and the javadoc for ResponseBuilder.location() says
```
        /**
         * Set the location.
         *
         * @param location the location. If a relative URI is supplied it will be
         *                 converted into an absolute URI by resolving it relative to the
         *                 base URI of the application (see {@link UriInfo#getBaseUri}).
         *                 If {@code null} any existing value for location will be removed.
         * @return the updated response builder.
         */
```
so if ResponseBuilder.location() is implemented correctly, then Response.created() already adheres to the updated javadoc. 

-Ron

**Comment by ronsigal** [comment]
For the record, I also submitted a test for the TCK: https://github.com/eclipse-ee4j/jakartaee-tck/pull/135.

**Comment by mkarg** [comment]
oops... I hate the "Close and commit" button... ;-)

**Comment by mkarg** [comment]
@ronsigal Let's see what other vendors think. I just invited them to share their opinion.

**Comment by mkarg** [comment]
I'm convinced that @ronsigal is right and it is simply a typo in the spec. So if we fix the spec as proposed (i. e. keep the implementation), then the actual behaviour would be backwords compatible. As a result, we could add it to JAX-RS 2.2.

**Comment by ronsigal** [comment]
Thanks, everyone.

**Comment by mkarg** [comment]
Do we need to mention this in the spec, at least in the history appendix?

**Comment by chkal** [comment]
IMO adding a note to the history appendix is sufficient.

**Comment by mkarg** [comment]
> IMO adding a note to the history appendix is sufficient.

I drafted https://github.com/eclipse-ee4j/jaxrs-api/pull/936. WDYT?

**Pull request merged**
