### PR TITLE
Changed groupId and artifactId. Fixes #663 (EE4J)

### LINKED ISSUE #663: Change Maven coordinates
All current API libraries shipped must be distributed to Maven Central under a sub-package of the `jakarta` groupId. Before the first release Maven coordinates of this project must be changed as it's described [here](https://github.com/eclipse-ee4j/ee4j/wiki/New-Maven-Coordinates).

### PR DESCRIPTION
**Pull request by ggam**
Signed-off-by: Guillermo González de Agüero <z06.guillermo@gmail.com>

### CODE REVIEW

**Comment by arjantijms** [comment]
@ggam There was a merge conflict, can you double check I merged it well? thx!

**Comment by ggam** [comment]
You are right, I cherry picked my commit from master which has a different version. Thanks for taking care of it! Sadly it seems it has detected a change also on the parent artifact.

Let me resubmit the PR...

**Comment by spericas** [comment]
@arjantijms @ggam I agree with @mkarg. I understand that 2 weeks may be too long in some cases, but for those exceptions can be requested.

**Comment by arjantijms** [comment]
@spericas 

🤔

**Pull request closed without merging**
