### PR TITLE
Excluding JRE's implied JAXB implementation with JDK11+

### PR DESCRIPTION
**Pull request by senivam**
As JDK11+ explicitly requests a particular version of JAXB, it is more safe to exclude the version of JAXB implicitly contained by the JRE itself.

### CODE REVIEW

**Comment by senivam** [comment]
pom.xml is reduced only to lines:

lines changed:
`<release>9</release>`
to
`<source>9</source>
<target>9</target>`

Because using <release> makes the JDK to use only those libraries which are a part of  JDK (9). Hovewer JDK 11 does not contain javax.xml.bind. We provide it externally (using maven dependency). Thus it is preferable no to limit JDK only to internal API because JDK 11 will not find required classes.

**Comment by mkarg** [comment]
I don't get it. Christian do you know what he means? I am willing to believe he is right, I just don't understand the actual detail.

**Comment by chkal** [comment]
Ah, I think I understand the problem. The `release` argument works like this:

> For the platforms predefined in javac, --release N is equivalent to -source N -target N -bootclasspath &lt;bootclasspath-from-N&gt;

So basically using `release=9` means that we are getting the bootclasspath of JDK9 even if we are compiling with JDK11. But this also means that we are getting JAXB via the bootclasspath, although this profile adds JAXB as an additional dependency (because JAXB isn't available with JDK11).

I think it is fine to merge this PR. I guess using the `release` flag doesn't really make sense in this profile. Especially because the real target JDK is actually 8.

**Comment by chkal** [comment]
@senivam It would be great if you could fix the indentation. Looks like some mixed spaces/tabs problem. See the diff in the files changed tab.

**Comment by mkarg** [comment]
@chkal Ah I see, right! I missed that! Thanks! Would be cool if future PR description would be a bit more elaborate, so voting gets easier. :-)

**Comment by mkarg** [comment]
@senivam Thanks for this PR! I have adjusted title and description to make a bit more clear what it talks about. Please confirm that the new text now matches the core point of your proposal. :-)

**Comment by senivam** [comment]
@mkarg, @chkal indentation is fixed, title adjustment reflects what I've meant, thank you :)

**Comment by mkarg** [comment]
@senivam Assuming that `EE4J_8` will be published before the minimum release review duration of two weeks (!) is over, and given the fact that your PR is not *essential* for EE4J_8 (since we will skip JDK 11 support for *this* release anyways), you maybe like to switch target branch to `master`?

**Comment by mkarg** [comment]
@spericas @chkal We dont' need this for OSSRH staging, so we have two options: Staging *without* (i. e. I will change target branch of this PR to `master`) *or* including before staging (i. e. we should *fast-track* this PR). Opinions?

**Comment by jansupol** [comment]
Should this be a blocker for #690, I vote for fast tracking this.

**Comment by mkarg** [comment]
@jansupol It is not a blocker as the POM skips this dependencies now that we decided not compile on JDK11, but it is just "dirty" because the dependencies actually are contained in the JDK11 profile of the POM file.

**Comment by chkal** [comment]
I don't think we need to merge this before staging the release. The affected profile isn't active during the release, so I don't see any reason to merge this now.

**Comment by mkarg** [comment]
*Replaced by https://github.com/eclipse-ee4j/jaxrs-api/pull/704*

**Pull request closed without merging**
