### PR TITLE
Fix issue 581: Problem with RuntimeDelegate.getInstance()

### PR DESCRIPTION
**Pull request by NiklasMehner**
This implements a fix for issue #581: Problem with RuntimeDelegate.getInstance().

### CODE REVIEW

**Comment by mkarg** [comment]
@NiklasMehner I think it would be best if you get different vendors into the boat for a review (Jersey, RESTeasy, CXF, etc.) so all of them are ok with your proposal. If you know committers from those teams just add them as reviewers on this page in the upper right "Reviewers" panel. Otherwise, I can suggest some reviewers.

**Comment by NiklasMehner** [comment]
@mkarg Unfortunately I don't know any committers from the vendors. Also I don't have the permission to add reviewers to a pull request. So if you could add the relevant persons that'd be great. Thanks, Niklas

**Comment by mkarg** [comment]
@NiklasMehner For Jersey you can ask our project lead Santiago (spericas). For all other vendors I am currently setting up a list of "official" contacts. If this is ok for you, I will suspend this PR unless I found the definitive contacts?

**Comment by NiklasMehner** [comment]
@mkarg Yes, i'm fine with suspending the PR

@spericas Could you please review the changes from a Jersey perspective? Thanks a lot, Niklas

**Comment by mkarg** [comment]
@NiklasMehner Instead of prosa, you can simply add reviewers using the "Reviewers" panel in the upper right corner of the PR page on Github. :-)

**Comment by NiklasMehner** [comment]
@mkarg See my comment above: I don't seem to have the permission to add reviewers.

**Comment by mkarg** [comment]
@NiklasMehner Oops, seems only Committers can add reviewers. Strange. Ok, I can do that for you, once I found out the Github names I'm still searching for... (anybody knows a "People Search" on Github?).

**Comment by spericas** [comment]
Don't know about the original intent of that default delegate. Let me ask around.

**Comment by mkarg** [comment]
Okay so we have a "go" from three vendors (Apache, IBM, Oracle) so I assign this to me for future merge once the discussion about future branch names is over. :-)

**Comment by chkal** [comment]
@mkarg: This PR is targeted at `2.2-SNAPSHOT` and the proposal is to merge exactly this branch into `master`. So I guess it would be save to merge this PR now. Whether we follow the proposal and merge the branch into `master` can be decided later and shouldn't block this PR.

BTW: This PR has three +1 votes. So it would be fine to merge it if we use the voting rules discussed on the list. :smiley:

**Pull request merged**
