### PR TITLE
Automatically trigger nightly builds

### PR DESCRIPTION
**Pull request by mkarg**
Fixes nightly builds, so they actually run _automatically_ now (not just manually).

**Review Period: As this is a pure project configuration PR, I will merge this PR _as soon as_ two reviewers approved it.**

### CODE REVIEW

**Comment by mkarg** [comment]
If nothing else fails, nightly builds of `EE4J_8` should *automatically* work now. Every night Jenkins checks the source for changes. If changed, it builds, and pushes the result on Nexus:
* Jenkins: https://ci.eclipse.org/jaxrs/job/Nightly%20Build/job/EE4J_8/
* Nexus: https://repo.eclipse.org/content/repositories/jax-rs-api-snapshots/javax/ws/rs/javax.ws.rs-examples/2.1.1-SNAPSHOT/

So all interested parties can now add Eclipse Foundation's Nexus as an additional repository to lookup and pull EE4J_8 as a SNAPSHOT dependency. :-)

**Comment by chkal** [comment]
That's awesome! Thanks, @mkarg!

**Comment by spericas** [comment]
Thanks for taking care of this. 

But I see 2.2-SNAPSHOT was pushed as well:

https://repo.eclipse.org/content/repositories/jax-rs-api-snapshots/javax/ws/rs/javax.ws.rs-api/2.2-SNAPSHOT/

Was that an accident?

**Comment by mkarg** [comment]
I need to check that.

**Comment by mkarg** [comment]
EF legal dept. confirmed they are currently working with their admins to protect the nightly builds from public access.

**Comment by spericas** [comment]
@mkarg Ok, thanks for following up and updating on the status.

**Pull request merged**
