### PR TITLE
Adding Expect header of HTTP/1.1 spec

### LINKED ISSUE #900: HttpHeader for Expect
will it be possible to add after [this line](https://github.com/eclipse-ee4j/jaxrs-api/blob/739605d01db73c522779dd43897bf86c8709ad2d/jaxrs-api/src/main/java/jakarta/ws/rs/core/HttpHeaders.java#L199) HttpHeader for Expect? 
```
    /**
     * See <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.20">HTTP/1.1 documentation</a>.
     */
    public static final String EXPECT = "Expect";
```

this is required to provide support for HTTP 100-continue handling (see related [Jersey bug](https://github.com/eclipse-ee4j/jersey/issues/4536) about this)

### PR DESCRIPTION
**Pull request by senivam**
Closes #900

### CODE REVIEW

**Comment by senivam** [comment]
fixes #900

**Review by mkarg — APPROVED** [review]
Thank you, Maxim.

**Review by chkal — APPROVED** [review]

**Review by jansupol — APPROVED** [review]

**Comment by andymc12** [comment]
@mkarg, this PR has been approved and the two week review period has passed.  Any reason not to merge?  Thanks

**Comment by mkarg** [comment]
> @mkarg, this PR has been approved and the two week review period has passed. Any reason not to merge? Thanks

Thanks for your kind reminder! I just forgot it, actually. :-)

**Pull request merged**
