### PR TITLE
Cleanup of unit tests

### PR DESCRIPTION
**Pull request by spericas**
Cleanup of unit tests: (1) Use Mockito where possible (2) Base class for tests that use RuntimeDelegate (3) Minor reformatting.

Requesting fast track.

Signed-off-by: Santiago Pericasgeertsen <santiago.pericasgeertsen@oracle.com>

### CODE REVIEW

**Review by andymc12 — DISMISSED** [review]
LGTM - thanks!

**Review by chkal — APPROVED** [review]
Looks good. Thanks!

**Comment by andymc12** [comment]
@spericas it looks like something went wrong with the merge - now this PR is pulling in my changes for multipart and your changes regarding `@Context` injection that should already be in master.  Maybe a rebase on master and force push would solve this?

**Comment by spericas** [comment]
> @spericas it looks like something went wrong with the merge - now this PR is pulling in my changes for multipart and your changes regarding `@Context` injection that should already be in master. Maybe a rebase on master and force push would solve this?

 Yes, there was a merge conflict, but this outcome is not what I had in mind. Let me try to fix this.

**Review by andymc12 — APPROVED** [review]
Still LGTM - thanks!

**Review by chkal — APPROVED** [review]

**Review by mkarg — APPROVED** [review]

**Pull request merged**
