### PR TITLE
Removed references to JSRs

### PR DESCRIPTION
**Pull request by thadumi**
According to the issue  Spec: Todo  #804 , I removed the last reference to JSR within the specification document. 

In the discussion #843 we deiced that Expert Group Members and Acknowledgements may stay as-is.

### CODE REVIEW

**Comment by spericas** [comment]
@thadumi Can you please take a look at https://www.eclipse.org/legal/ECA.php if you haven't already?

**Comment by thadumi** [comment]
> @thadumi Can you please take a look at https://www.eclipse.org/legal/ECA.php if you haven't already?

I have already signed the ECA

**Comment by spericas** [comment]
> > @thadumi Can you please take a look at https://www.eclipse.org/legal/ECA.php if you haven't already?
> 
> I have already signed the ECA

Verification seems to be failing here:

https://accounts.eclipse.org/legal/eca/validation/27315

Is that the same e-mail address?

**Comment by thadumi** [comment]
> > > @thadumi Can you please take a look at https://www.eclipse.org/legal/ECA.php if you haven't already?
> > 
> > 
> > I have already signed the ECA
> 
> Verification seems to be failing here:
> 
> https://accounts.eclipse.org/legal/eca/validation/27315
> 
> Is that the same e-mail address?

No, actually I'm using a different email for my profile on Eclipse. 
If I add a second email on GitHub it should be fine, right?

**Comment by thadumi** [comment]
> > > > @thadumi Can you please take a look at https://www.eclipse.org/legal/ECA.php if you haven't already?
> > > 
> > > 
> > > I have already signed the ECA
> > 
> > 
> > Verification seems to be failing here:
> > https://accounts.eclipse.org/legal/eca/validation/27315
> > Is that the same e-mail address?
> 
> No, actually I'm using a different email for my profile on Eclipse.
> If I add a second email on GitHub it should be fine, right?

I have just checked and my primary email (not the public one) is the same on github and eclipse.

**Comment by spericas** [comment]
> > > > > @thadumi Can you please take a look at https://www.eclipse.org/legal/ECA.php if you haven't already?
> > > > 
> > > > 
> > > > I have already signed the ECA
> > > 
> > > 
> > > Verification seems to be failing here:
> > > https://accounts.eclipse.org/legal/eca/validation/27315
> > > Is that the same e-mail address?
> > 
> > 
> > No, actually I'm using a different email for my profile on Eclipse.
> > If I add a second email on GitHub it should be fine, right?
> 
> I have just checked and my primary email (not the public one) is the same on github and eclipse. I tried to remove the second email (the one which doesn't match the Eclipse account) but it seams that the ECA check is still using the old one.

Not sure what to suggest. Anyone with more experience with ECA's can help here?

**Comment by mkarg** [comment]
> Not sure what to suggest. Anyone with more experience with ECA's can help here?

The commit was performed with the email address `dumitrescu_theodor_a_@****.it`, for which **no** ECA was signed (see https://accounts.eclipse.org/legal/eca/validation/27315). Theodor, if that is wrong, then please directly contact the EMO.

**Comment by thadumi** [comment]
> > Not sure what to suggest. Anyone with more experience with ECA's can help here?
> 
> The commit was performed with the email address `dumitrescu_theodor_a_@****.it`, for which **no** ECA was signed (see https://accounts.eclipse.org/legal/eca/validation/27315). Theodor, if that is wrong, then please directly contact the EMO.

Couldn't I just close this pull request and open another with the correct email?

**Comment by mkarg** [comment]
> > The commit was performed with the email address `dumitrescu_theodor_a_@****.it`, for which **no** ECA was signed (see https://accounts.eclipse.org/legal/eca/validation/27315). Theodor, if that is wrong, then please directly contact the EMO.
> 
> Couldn't I just close this pull request and open another with the correct email?

No, this would not help. The pull request is not the problem. The problem is in the commits. You have to modify the `author` field of *each* commit to point to the right account using the right email address. Then use `push -f` to force overwriting the commits *within the existing PR*.

**Comment by thadumi** [comment]
> No, this would not help. The pull request is not the problem. The problem is in the commits. You have to modify the `author` field of _each_ commit to point to the right account using the right email address. Then use `push -f` to force overwriting the commits _within the existing PR_.

Thanks for the hint. I used rebase and commit --amend for fixing it

**Comment by mkarg** [comment]
> Thanks for the hint. I used rebase and commit --amend for fixing it

...and apparently it *did* solve the problem. ;-)

**Pull request merged**
